language: python

python:
  - "3.6"

before_install:
  - "pip install -U pip"
  - "python setup.py install"

install:
  - pip install -r requirements.txt

script:
  - python -m unittest linked_list/test_singly_linked_list.py

branches:
  only:
    - master